### ISSUE TITLE
KeyError: 'model_file' using safety.sensitive model

### ISSUE THREAD

**Issue by EternalDusk** [hyunwoongko/openchat#45]
(Using Ubuntu on WSL, other models work so I don't believe WSL is the issue. OpenChat will not load on windows.)

>>> from openchat import OpenChat
>>> OpenChat(model="safety.sensitive", device="cpu")

                                  ____   ____   ______ _   __   ______ __  __ ___   ______
                                 / __ \ / __ \ / ____// | / /  / ____// / / //   | /_  __/
                                / / / // /_/ // __/  /  |/ /  / /    / /_/ // /| |  / /
                               / /_/ // ____// /___ / /|  /  / /___ / __  // ___ | / /
                               \____//_/    /_____//_/ |_/   \____//_/ /_//_/  |_|/_/

                                                   ... LOADING ...

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dusk/.local/lib/python3.8/site-packages/openchat/openchat.py", line 24, in __init__
    self.agent = self.create_agent_by_name(
  File "/home/dusk/.local/lib/python3.8/site-packages/openchat/openchat.py", line 87, in create_agent_by_name
    return SensitiveAgent(name, device, maxlen)
  File "/home/dusk/.local/lib/python3.8/site-packages/openchat/agents/safety.py", line 111, in __init__
    model=create_agent_from_opt_file(option),
  File "/home/dusk/.local/lib/python3.8/site-packages/parlai/core/agents.py", line 361, in create_agent_from_opt_file
    model_file = opt['model_file']
KeyError: 'model_file'

I don't know quite what is causing this, any help is appreciated!

**Comment by EternalDusk** [comment]
Tested this again on a clean Ubuntu installation, safety models are not working. Same error as before.
